### ISSUE TITLE
i don't know error

### ISSUE THREAD

**Issue by kdyoung100** [iqbal-lab-org/minos#115]
raceback (most recent call last):
  File "/home/tools/anaconda3/lib/python3.7/site-packages/bio_minos-0.12.3-py3.7.egg/minos/adjudicator.py", line 148, in build_output_dir
    os.mkdir(self.outdir)
FileExistsError: [Errno 17] File exists: '/home/kdyoung/01.Variant/10.KNTA/Batch01/1/01.snp/04.minos_vcf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tools/anaconda3/bin/minos", line 33, in <module>
    sys.exit(load_entry_point('bio-minos==0.12.3', 'console_scripts', 'minos')())
  File "/home/tools/anaconda3/lib/python3.7/site-packages/bio_minos-0.12.3-py3.7.egg/minos/__main__.py", line 300, in main
    args.func(args)
  File "/home/tools/anaconda3/lib/python3.7/site-packages/bio_minos-0.12.3-py3.7.egg/minos/tasks/adjudicate.py", line 28, in run
    adj.run()
  File "/home/tools/anaconda3/lib/python3.7/site-packages/bio_minos-0.12.3-py3.7.egg/minos/adjudicator.py", line 199, in run
    self.build_output_dir()
  File "/home/tools/anaconda3/lib/python3.7/site-packages/bio_minos-0.12.3-py3.7.egg/minos/adjudicator.py", line 155, in build_output_dir
    f"Output directory {self.outdir} already exists. "
Exception: Output directory /home/kdyoung/01.Variant/10.KNTA/Batch01/1/01.snp/04.minos_vcf already exists. Rerun command with --force flag if you are OK with overwriting it

**Comment by martinghunt** [comment]
What is in the log file?
Did you get any error messages in your terminal?

**Comment by kdyoung100** [comment]
in the log file commend and my terminal not messages ! 

![image](https://user-images.githubusercontent.com/103394452/182268715-47d4cb4d-358c-4914-bbfb-3737d5bbbacb.png)

**Comment by kdyoung100** [comment]
[log.txt](https://github.com/iqbal-lab-org/minos/files/9238211/log.txt)

**Comment by martinghunt** [comment]
Could you please update to the latest release 0.12.4 and then check if your install works on the new test data?
https://github.com/iqbal-lab-org/minos/wiki/Minos-test-data
